version: '3.5'

services:
  tourguide:
    image: tourguide:0.0.1
    ports:
      - "9005:9005"
    networks: 
      - backend
    
  tourguide_gpsUtil:
    image: gps_util:0.0.1
    ports:
      - "9006:9006"
    networks: 
      - backend

  tourguide_rewardCentral:
    image: reward_central:0.0.1
    ports:
      - "9007:9007"
    networks: 
      - backend

  tourguide_tripPricer:
    image: trip_pricer:0.0.1
    ports:
      - "9008:9008"
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"
